name: Create Issue on Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get pull request details and create issue content
        id: get_pr_details
        run: |
          # 获取 PR 标题和描述
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"
          
          # 获取变更文件列表并格式化为字符串
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | tr '\n' ', ')
          
          # 创建 issue 内容，包括标题、描述和变更文件列表
          ISSUE_CONTENT="**PR 标题:** $PR_TITLE\n\n**PR 描述:**\n$PR_BODY\n\n**更改的内容:**\n$CHANGED_FILES"
          
          echo "issue_content<<EOF" >> $GITHUB_ENV
          echo "$ISSUE_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name : Create an issue from the pull request 
        id : create_issue 
        uses : peter-evans/create-issue-from-file@v3 
        with :
            title : '${{ github.event.pull_request.title }} Issue 提交'
            body : "${{ env.issue_content }}"
            labels : 'Pull Request'

      - name : Comment on the pull request with issue link 
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run : |
            ISSUE_URL="${{ steps.create_issue.outputs.issue_url }}"
            gh pr comment "${{ github.event.pull_request.number }}" --body="相关的Issue已创建：[$ISSUE_URL]($ISSUE_URL)"
